# region - model
model:
  Generator:     C2N_G
  Discriminator: C2N_D
  Denoiser:      CDnCNN_B

  color: BGR

  GAN_n_r: 32
# endregion - model

# region - common train
train:
  aug: 'rotflip'
# endregion - common train

# region - train_GAN
train_GAN:
  n_epoch: 36
  batch_size: 36
  imsize: 96
  n_patch: 36000

  loss:
    GAN_adv: 1.*wGAN-GP
    GAN_con: 1e-2*batch_zero_mean

  lr: 1e-4
  lr_sched:
    type: step
    step:
      step_size: 3
      gamma: 0.8
  
  dset_N: prep_SIDD_Medium_sRGB
  dset_CL: prep_SIDD_Medium_sRGB
  noise_additive: None
  salt_pepper: None
  crop_patch: True
  
  preload: False
# endregion - train_GAN

# region - train_DNer
train_DNer:
  n_epoch: 32
  batch_size: 16
  imsize: 96

  loss:
    DN: 1.*L1
  
  lr: 1e-4
  lr_sched:
    type: step
    step:
      step_size: 4
      gamma: 0.71
  
  dset: prep_SIDD_Medium_sRGB
  noise_additive: None
  salt_pepper: None
  crop_patch: True

  dset_gen_CL: None
  n_patch_gen: 18000
  loadname_CLtoN: None
# endregion - train_DNer
